name: Build and Release Wails App

on:
  push:
    tags:
      - 'v*'  # Still trigger on version tags

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run lint
        run: npm run lint
        working-directory: ./frontend

      - name: Run format check
        run: npm run format -- --check
        working-directory: ./frontend

      - name: Run type check
        run: npm run type-check
        working-directory: ./frontend

  build-macos:
    needs: validate
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Build macOS app
        run: wails build -platform darwin/universal

      - name: Create dist directory
        run: mkdir -p dist

      - name: Create .dmg installer
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Jot Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "jot.app" 200 190 \
            --hide-extension "jot.app" \
            --app-drop-link 600 185 \
            --no-internet-enable \
            dist/Jot-macOS.dmg \
            build/bin/jot.app

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: Jot-macOS
          path: dist/Jot-macOS.dmg

  build-windows:
    needs: validate
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to path
        run: echo "$env:USERPROFILE\\go\\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Build Windows app
        run: wails build -platform windows/amd64

      - name: Create dist directory
        run: New-Item -ItemType Directory -Force -Path dist

      - name: Copy Windows executable
        run: Copy-Item -Path build/bin/jot.exe -Destination dist/Jot-Windows.exe

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: Jot-Windows
          path: dist/Jot-Windows.exe

  release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: Jot-macOS
          path: ./release-assets

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Jot-Windows
          path: ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
